### ISSUE TITLE
What's the relationship between F9 microkernel and BitSec

### ISSUE THREAD

**Issue by BaikalHu** [f9micro/f9-kernel#149]
I'm learning f9-kernel on STM32F429I board, and read <Secure Microkernel for Deeply Embedded Devices.pdf>. 
F9 and BitSec are the 3th generation microkernel, and BitSec is learnt from uVisor, focus on security.
As I read the f9-kernel source code, f9-kernel use MPU in Cortex-M3/4 to do it. I think BitSec also base on MPU. So what's the relationship between f9 and BitSec? what's the differences between them? what's the BitSec's advantage?

**Comment by jserv** [comment]
From the perspective of microkernel design, F9 microkernel belongs to second generation so does [L4Ka](http://www.l4ka.org/projects/pistachio). BitSec was constructed with capability model, which is a major feature in 3rd generation microkernel. The source code of BitSec hypervisor is not yet publicly available though.
