### ISSUE TITLE
f9-kernel wiki

### ISSUE THREAD

**Issue by BaikalHu** [f9micro/f9-kernel#151]
In http://wiki.csie.ncku.edu.tw/embedded/f9-kernel#overview  page:

    3.
    Base 0x80001000 1000 0000 0000 0000 0001 0000 0000 0000
    Size 0x20000000 0010 0000 0000 0000 0000 0000 0000 0000
    2^Log2(Base) < Size => Create a fpage with 2^Log2(Base)
    Base = 0x80001000 + 0x00001000 = 0x80010000

The last line should be : Base = 0x80001000 + 0x00001000 = 0x80002000.

**Comment by jserv** [comment]
The website wiki.csie.ncku.edu.tw is not official F9 wiki, and please do submit bug report and software quality specific issues here.

**Comment by BaikalHu** [comment]
Got it.
