### ISSUE TITLE
support qemu or not ?

### ISSUE THREAD

**Issue by jeffrey67** [f9micro/f9-kernel#152]
I am newbie in f9-kernel. Does f9-kernel support qemu or not? if support, is there any guide how to use.
I found the QEMU_DIR in Makefile, but i can not found the dir.

**Comment by jserv** [comment]
@jeffrey67, You can check file `.travis.yml`, which contains the procedure to build F9 microkernel for stm32-p103/QEMU and verify.

**Comment by xiangzhai** [comment]
@jserv please teach me how to debug #12 thanks a lot!
