### ISSUE TITLE
IPC specification (just a question)

### ISSUE THREAD

**Issue by Daparrag** [f9micro/f9-kernel#155]
Hi everyone

I would like to know which kind of IPC did you implement in the f9-kernel thanks you.

**Comment by jserv** [comment]
F9 implements typical L4 IPC messages which consist of the following kinds of parameters:
* `snd_reg` or `rcv_reg`: in-register (``short'') part of message
* `snd_msg` or `rcv_msg`: in-memory (``long'') part of message

**Comment by Daparrag** [comment]
thanks you for your answer.
