### ISSUE TITLE
L4 kernel API specification

### ISSUE THREAD

**Issue by ab1aw** [f9micro/f9-kernel#156]
Which of the L4 API specifications does F9 implement?  
Is it one of the following as documented at http://l4hq.org/kernels/? 

Version 2
Version X.0
Version X.2 (a.k.a. Version 4)
NICTA N series
OKL4 series
Fiasco.OC

Thank you.

**Comment by jserv** [comment]
Partial L4 API X.2 was implemented in F9 microkernel by referring L4Ka::Pistachio internals.

**Comment by ab1aw** [comment]
Thank you.  I will refer to the documentation located at: http://www.l4ka.org/65.php
