### ISSUE TITLE
add f9-kernel to github topic "l4-microkernel"

### ISSUE THREAD

**Issue by froh** [f9micro/f9-kernel#162]
github allows to categorize repos into topics.

this repo is [missing :-) in the l4-microkernel topic](https://github.com/topics/l4-microkernel)

It is straightforward to [add a repo to a topic](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics)

**Comment by jserv** [comment]
Thanks for the information. I have added the topics.
