### ISSUE TITLE
ambiguous user space function create_thread

### ISSUE THREAD

**Issue by georgekang** [f9micro/f9-kernel#91]
There should be a uniform definition of "create_thread".  
Now, we have two "create_thread".  It lets me confused.

static L4_ThreadId_t __USER_TEXT create_thread(user_struct *user, void (*func)(void));

L4_ThreadId_t __USER_TEXT
create_thread(void (*func)(void), bool new_space, int cpu, L4_Word_t spacectrl);

**Comment by jserv** [comment]
This issue is no longer valid since pager was introduced to manage the whole thread creation and address space.
